/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_saxonica_functions_extfn_PhpCall_PhpFunctionCall */

#ifndef _Included_com_saxonica_functions_extfn_PhpCall_PhpFunctionCall
#define _Included_com_saxonica_functions_extfn_PhpCall_PhpFunctionCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_saxonica_functions_extfn_PhpCall_PhpFunctionCall
 * Method:    _phpCall
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_saxonica_functions_extfn_PhpCall_00024PhpFunctionCall__1phpCall
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
